version: '3.1'

services:
  # MYSQL
  mysql_report_database:
    image: mysql
    container_name: mysql_report_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DATABASE_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE_NAME
    ports:
      - "${MYSQL_DATABASE_PORT}:3306"

  # POSTGRESQL
  postgresql_report_database:
    image: postgres
    restart: always
    container_name: postgresql_report_database
    ports:
      - "${POSTGRES_DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_DATABASE_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE_NAME
