version: '3.1'

services:
  # MYSQL
  mysql_report_database:
    image: mysql
    container_name: mysql_report_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DATABASE_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE_NAME
    ports:
      - "${MYSQL_DATABASE_PORT}:3306"

  # POSTGRESQL
  postgresql_report_database:
    image: postgres
    restart: always
    container_name: postgresql_report_database
    ports:
      - "${POSTGRES_DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_DATABASE_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE_NAME

  # MONGODB
  mongodb_report_database:
    container_name: mongodb_report_database
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DATABASE_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DATABASE_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE_NAME
      DATABASE_USER: $MONGO_DATABASE_USERNAME
      DATABASE_PASS: $MONGO_DATABASE_PASSWORD
      DATABASE_NAME: $MONGO_DATABASE_NAME
    volumes:
      - ./src/configs/databases/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "${MONGO_DATABASE_PORT}:27017"

  # Scylla
  scylla_report_database:
    container_name: scylla_report_database
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla_report_database --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./src/configs/databases/scylla.yaml:/etc/scylla/scylla.yaml"
